<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\ReferenceCredentials.Sql\ReferenceCredentials.Sql.csproj" />
    <PackageReference Include="Fdw.Messages" />
  </ItemGroup>
</Project>
