<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\ReferenceHosting.Middleware\ReferenceHosting.Middleware.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <PropertyGroup>
    <Include>[ReferenceHosting.Middleware]*</Include>
    <Exclude>[xunit.*]*,[Moq]*,[Shouldly]*</Exclude>
  </PropertyGroup>
</Project>
